#!/usr/bin/env bash

MARKDOWN_IN="$1"
[ -z "$MARKDOWN_IN" ] && { echo "Script requires one markdown argument."; exit 1; }

set -o errexit
set -o xtrace

OUTPUT_DIR="site_generated"
[ -d "$OUTPUT_DIR" ] && rm -r "$OUTPUT_DIR"
mkdir "$OUTPUT_DIR"

pandoc \
  --mathml \
  --template template.html \
  --toc \
  --toc-depth 1 \
  -t chunkedhtml \
  --split-level 1 \
  --chunk-template "%i.html" \
  -o "$OUTPUT_DIR/site.zip" \
  "$MARKDOWN_IN"

unzip -o "$OUTPUT_DIR/site.zip" -d /var/www/html/
# Remove in-page hash fragments from TOC links on the landing page so links open at page top
sed -E -i 's/(href="[^"#]+\.html)#[^"]+"/\1"/g' /var/www/html/index.html || true
gzip -k -9 -f js/*.js
gzip -k -9 -f js/*.css
cp -r js /var/www/html/
cp -r vr_assets /var/www/html/
cp -r images /var/www/html/

